linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - misspell
    - dogsled
    - nakedret
    - prealloc
    - gocritic
    - funlen
    - lll
    - nlreturn

linters-settings:
  funlen:
    lines: 70
    statements: 50

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - dupl
  exclude-dirs:
    - lua
    - mocks
    - tmp