services:
  tarantool:
    image: tarantool/tarantool:3.7
    ports:
      - "3303:3301"
    volumes:
      - ./.docker/config.yaml:/default-config.yaml
      - tarantool-data:/var/lib/tarantool
    restart: unless-stopped

volumes:
  tarantool-data: