// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/tarantool/go-tarantool/v3"
	"github.com/tarantool/go-tarantool/v3/pool"
	"sync"
	"time"
)

// Ensure, that PoolerMock does implement Pooler.
// If this is not the case, regenerate this file with moq.
var _ Pooler = &PoolerMock{}

// PoolerMock is a mock implementation of Pooler.
//
//	func TestSomethingThatUsesPooler(t *testing.T) {
//
//		// make and configure a mocked Pooler
//		mockedPooler := &PoolerMock{
//			AddFunc: func(ctx context.Context, instance pool.Instance) error {
//				panic("mock out the Add method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CloseGracefulFunc: func() error {
//				panic("mock out the CloseGraceful method")
//			},
//			ConfiguredTimeoutFunc: func(mode pool.Mode) (time.Duration, error) {
//				panic("mock out the ConfiguredTimeout method")
//			},
//			ConnectedNowFunc: func(mode pool.Mode) (bool, error) {
//				panic("mock out the ConnectedNow method")
//			},
//			DoFunc: func(req tarantool.Request, mode pool.Mode) tarantool.Future {
//				panic("mock out the Do method")
//			},
//			NewPreparedFunc: func(expr string, mode pool.Mode) (*tarantool.Prepared, error) {
//				panic("mock out the NewPrepared method")
//			},
//			NewStreamFunc: func(mode pool.Mode) (*tarantool.Stream, error) {
//				panic("mock out the NewStream method")
//			},
//			NewWatcherFunc: func(key string, callback tarantool.WatchCallback, mode pool.Mode) (tarantool.Watcher, error) {
//				panic("mock out the NewWatcher method")
//			},
//			RemoveFunc: func(name string) error {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedPooler in code that requires Pooler
//		// and then make assertions.
//
//	}
type PoolerMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, instance pool.Instance) error

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CloseGracefulFunc mocks the CloseGraceful method.
	CloseGracefulFunc func() error

	// ConfiguredTimeoutFunc mocks the ConfiguredTimeout method.
	ConfiguredTimeoutFunc func(mode pool.Mode) (time.Duration, error)

	// ConnectedNowFunc mocks the ConnectedNow method.
	ConnectedNowFunc func(mode pool.Mode) (bool, error)

	// DoFunc mocks the Do method.
	DoFunc func(req tarantool.Request, mode pool.Mode) tarantool.Future

	// NewPreparedFunc mocks the NewPrepared method.
	NewPreparedFunc func(expr string, mode pool.Mode) (*tarantool.Prepared, error)

	// NewStreamFunc mocks the NewStream method.
	NewStreamFunc func(mode pool.Mode) (*tarantool.Stream, error)

	// NewWatcherFunc mocks the NewWatcher method.
	NewWatcherFunc func(key string, callback tarantool.WatchCallback, mode pool.Mode) (tarantool.Watcher, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(name string) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Instance is the instance argument value.
			Instance pool.Instance
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CloseGraceful holds details about calls to the CloseGraceful method.
		CloseGraceful []struct {
		}
		// ConfiguredTimeout holds details about calls to the ConfiguredTimeout method.
		ConfiguredTimeout []struct {
			// Mode is the mode argument value.
			Mode pool.Mode
		}
		// ConnectedNow holds details about calls to the ConnectedNow method.
		ConnectedNow []struct {
			// Mode is the mode argument value.
			Mode pool.Mode
		}
		// Do holds details about calls to the Do method.
		Do []struct {
			// Req is the req argument value.
			Req tarantool.Request
			// Mode is the mode argument value.
			Mode pool.Mode
		}
		// NewPrepared holds details about calls to the NewPrepared method.
		NewPrepared []struct {
			// Expr is the expr argument value.
			Expr string
			// Mode is the mode argument value.
			Mode pool.Mode
		}
		// NewStream holds details about calls to the NewStream method.
		NewStream []struct {
			// Mode is the mode argument value.
			Mode pool.Mode
		}
		// NewWatcher holds details about calls to the NewWatcher method.
		NewWatcher []struct {
			// Key is the key argument value.
			Key string
			// Callback is the callback argument value.
			Callback tarantool.WatchCallback
			// Mode is the mode argument value.
			Mode pool.Mode
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockAdd               sync.RWMutex
	lockClose             sync.RWMutex
	lockCloseGraceful     sync.RWMutex
	lockConfiguredTimeout sync.RWMutex
	lockConnectedNow      sync.RWMutex
	lockDo                sync.RWMutex
	lockNewPrepared       sync.RWMutex
	lockNewStream         sync.RWMutex
	lockNewWatcher        sync.RWMutex
	lockRemove            sync.RWMutex
}

// Add calls AddFunc.
func (mock *PoolerMock) Add(ctx context.Context, instance pool.Instance) error {
	if mock.AddFunc == nil {
		panic("PoolerMock.AddFunc: method is nil but Pooler.Add was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Instance pool.Instance
	}{
		Ctx:      ctx,
		Instance: instance,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, instance)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedPooler.AddCalls())
func (mock *PoolerMock) AddCalls() []struct {
	Ctx      context.Context
	Instance pool.Instance
} {
	var calls []struct {
		Ctx      context.Context
		Instance pool.Instance
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *PoolerMock) Close() error {
	if mock.CloseFunc == nil {
		panic("PoolerMock.CloseFunc: method is nil but Pooler.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedPooler.CloseCalls())
func (mock *PoolerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CloseGraceful calls CloseGracefulFunc.
func (mock *PoolerMock) CloseGraceful() error {
	if mock.CloseGracefulFunc == nil {
		panic("PoolerMock.CloseGracefulFunc: method is nil but Pooler.CloseGraceful was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCloseGraceful.Lock()
	mock.calls.CloseGraceful = append(mock.calls.CloseGraceful, callInfo)
	mock.lockCloseGraceful.Unlock()
	return mock.CloseGracefulFunc()
}

// CloseGracefulCalls gets all the calls that were made to CloseGraceful.
// Check the length with:
//
//	len(mockedPooler.CloseGracefulCalls())
func (mock *PoolerMock) CloseGracefulCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCloseGraceful.RLock()
	calls = mock.calls.CloseGraceful
	mock.lockCloseGraceful.RUnlock()
	return calls
}

// ConfiguredTimeout calls ConfiguredTimeoutFunc.
func (mock *PoolerMock) ConfiguredTimeout(mode pool.Mode) (time.Duration, error) {
	if mock.ConfiguredTimeoutFunc == nil {
		panic("PoolerMock.ConfiguredTimeoutFunc: method is nil but Pooler.ConfiguredTimeout was just called")
	}
	callInfo := struct {
		Mode pool.Mode
	}{
		Mode: mode,
	}
	mock.lockConfiguredTimeout.Lock()
	mock.calls.ConfiguredTimeout = append(mock.calls.ConfiguredTimeout, callInfo)
	mock.lockConfiguredTimeout.Unlock()
	return mock.ConfiguredTimeoutFunc(mode)
}

// ConfiguredTimeoutCalls gets all the calls that were made to ConfiguredTimeout.
// Check the length with:
//
//	len(mockedPooler.ConfiguredTimeoutCalls())
func (mock *PoolerMock) ConfiguredTimeoutCalls() []struct {
	Mode pool.Mode
} {
	var calls []struct {
		Mode pool.Mode
	}
	mock.lockConfiguredTimeout.RLock()
	calls = mock.calls.ConfiguredTimeout
	mock.lockConfiguredTimeout.RUnlock()
	return calls
}

// ConnectedNow calls ConnectedNowFunc.
func (mock *PoolerMock) ConnectedNow(mode pool.Mode) (bool, error) {
	if mock.ConnectedNowFunc == nil {
		panic("PoolerMock.ConnectedNowFunc: method is nil but Pooler.ConnectedNow was just called")
	}
	callInfo := struct {
		Mode pool.Mode
	}{
		Mode: mode,
	}
	mock.lockConnectedNow.Lock()
	mock.calls.ConnectedNow = append(mock.calls.ConnectedNow, callInfo)
	mock.lockConnectedNow.Unlock()
	return mock.ConnectedNowFunc(mode)
}

// ConnectedNowCalls gets all the calls that were made to ConnectedNow.
// Check the length with:
//
//	len(mockedPooler.ConnectedNowCalls())
func (mock *PoolerMock) ConnectedNowCalls() []struct {
	Mode pool.Mode
} {
	var calls []struct {
		Mode pool.Mode
	}
	mock.lockConnectedNow.RLock()
	calls = mock.calls.ConnectedNow
	mock.lockConnectedNow.RUnlock()
	return calls
}

// Do calls DoFunc.
func (mock *PoolerMock) Do(req tarantool.Request, mode pool.Mode) tarantool.Future {
	if mock.DoFunc == nil {
		panic("PoolerMock.DoFunc: method is nil but Pooler.Do was just called")
	}
	callInfo := struct {
		Req  tarantool.Request
		Mode pool.Mode
	}{
		Req:  req,
		Mode: mode,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(req, mode)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedPooler.DoCalls())
func (mock *PoolerMock) DoCalls() []struct {
	Req  tarantool.Request
	Mode pool.Mode
} {
	var calls []struct {
		Req  tarantool.Request
		Mode pool.Mode
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// NewPrepared calls NewPreparedFunc.
func (mock *PoolerMock) NewPrepared(expr string, mode pool.Mode) (*tarantool.Prepared, error) {
	if mock.NewPreparedFunc == nil {
		panic("PoolerMock.NewPreparedFunc: method is nil but Pooler.NewPrepared was just called")
	}
	callInfo := struct {
		Expr string
		Mode pool.Mode
	}{
		Expr: expr,
		Mode: mode,
	}
	mock.lockNewPrepared.Lock()
	mock.calls.NewPrepared = append(mock.calls.NewPrepared, callInfo)
	mock.lockNewPrepared.Unlock()
	return mock.NewPreparedFunc(expr, mode)
}

// NewPreparedCalls gets all the calls that were made to NewPrepared.
// Check the length with:
//
//	len(mockedPooler.NewPreparedCalls())
func (mock *PoolerMock) NewPreparedCalls() []struct {
	Expr string
	Mode pool.Mode
} {
	var calls []struct {
		Expr string
		Mode pool.Mode
	}
	mock.lockNewPrepared.RLock()
	calls = mock.calls.NewPrepared
	mock.lockNewPrepared.RUnlock()
	return calls
}

// NewStream calls NewStreamFunc.
func (mock *PoolerMock) NewStream(mode pool.Mode) (*tarantool.Stream, error) {
	if mock.NewStreamFunc == nil {
		panic("PoolerMock.NewStreamFunc: method is nil but Pooler.NewStream was just called")
	}
	callInfo := struct {
		Mode pool.Mode
	}{
		Mode: mode,
	}
	mock.lockNewStream.Lock()
	mock.calls.NewStream = append(mock.calls.NewStream, callInfo)
	mock.lockNewStream.Unlock()
	return mock.NewStreamFunc(mode)
}

// NewStreamCalls gets all the calls that were made to NewStream.
// Check the length with:
//
//	len(mockedPooler.NewStreamCalls())
func (mock *PoolerMock) NewStreamCalls() []struct {
	Mode pool.Mode
} {
	var calls []struct {
		Mode pool.Mode
	}
	mock.lockNewStream.RLock()
	calls = mock.calls.NewStream
	mock.lockNewStream.RUnlock()
	return calls
}

// NewWatcher calls NewWatcherFunc.
func (mock *PoolerMock) NewWatcher(key string, callback tarantool.WatchCallback, mode pool.Mode) (tarantool.Watcher, error) {
	if mock.NewWatcherFunc == nil {
		panic("PoolerMock.NewWatcherFunc: method is nil but Pooler.NewWatcher was just called")
	}
	callInfo := struct {
		Key      string
		Callback tarantool.WatchCallback
		Mode     pool.Mode
	}{
		Key:      key,
		Callback: callback,
		Mode:     mode,
	}
	mock.lockNewWatcher.Lock()
	mock.calls.NewWatcher = append(mock.calls.NewWatcher, callInfo)
	mock.lockNewWatcher.Unlock()
	return mock.NewWatcherFunc(key, callback, mode)
}

// NewWatcherCalls gets all the calls that were made to NewWatcher.
// Check the length with:
//
//	len(mockedPooler.NewWatcherCalls())
func (mock *PoolerMock) NewWatcherCalls() []struct {
	Key      string
	Callback tarantool.WatchCallback
	Mode     pool.Mode
} {
	var calls []struct {
		Key      string
		Callback tarantool.WatchCallback
		Mode     pool.Mode
	}
	mock.lockNewWatcher.RLock()
	calls = mock.calls.NewWatcher
	mock.lockNewWatcher.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *PoolerMock) Remove(name string) error {
	if mock.RemoveFunc == nil {
		panic("PoolerMock.RemoveFunc: method is nil but Pooler.Remove was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(name)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedPooler.RemoveCalls())
func (mock *PoolerMock) RemoveCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
