name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  test:
    strategy:
      matrix:
        vm-os: [ubuntu-latest]
    runs-on: ${{ matrix.vm-os }}

    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.60

      - name: Create coverage file
        run: go test -coverprofile='coverage.txt' -covermode=atomic

      - name: Upload coverage file
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}